export const projectionStructureData = {
  fields: {
    gtin: {
      section: "Product",
      field: "GTIN",
      key: "gtin",
      type: "Text",
      filterData: ["equal to", "not equal to", "in", "not in", "is not assigned", "is assigned"],
      rules: ["required"],
    },
    "info.brand.name": {
      section: "Product",
      field: "Brand Name",
      key: "info.brand.name",
      type: "Text",
      filterData: ["equal to", "not equal to", "in", "not in", "is not assigned", "is assigned"],
      rules: ["required"],
    },
    "info.brand.manufacturer.name": {
      section: "Product",
      field: "Manufacturer Name",
      key: "info.brand.manufacturer.name",
      type: "Text",
      filterData: ["equal to", "not equal to"],
      rules: ["required"],
    },
    "info.importerDistributor": {
      section: "Product",
      field: "Importer/Distributor",
      key: "info.importerDistributor",
      type: "Text",
      filterData: ["equal to", "not equal to", "in", "not in", "is not assigned", "is assigned"],
      rules: ["required"],
    },
    "name.default": {
      section: "Product",
      field: "Product Name",
      key: "name.default",
      type: "Text",
      rules: ["required"],
    },
    "info.status.label": {
      section: "Product",
      field: "Status",
      key: "info.status.label",
      type: "Text",
      rules: ["required"],
    },
    "info.brand.brandOther": {
      section: "Product",
      field: "Brand Other",
      key: "info.brand.brandOther",
      type: "Text",
      rules: ["required"],
    },
    "info.nipType.label": {
      section: "Nutrients",
      field: "Nip Type",
      key: "info.nipType.label",
      type: "Dropdown",
      data: ["Standard", "No Nip", "Multiple Nip", "USA Nip", "Standard Plus", "EU Standard", "EU Standard Plus"],
      rules: ["required"],
    },
    "info.package.packageSize1.size": {
      section: "Product",
      field: "Package Size",
      key: "info.package.packageSize1.size",
      type: "Text",
      rules: ["required"],
    },
    "info.package.packageSize1.unit.label": {
      section: "Product",
      field: "Package Unit",
      key: "info.package.packageSize1.unit.label",
      type: "Dropdown",
      data: ["Grams", "mLs"],
      rules: ["required"],
    },
    "info.isConcentrate": {
      section: "Backend",
      field: "Is Concentrate",
      key: "info.isConcentrate",
      type: "Checkbox",
      rules: ["required"],
    },
    "info.serving.sold.unit.value": {
      section: "Nutrients",
      field: "Serving Size Unit - As Sold",
      key: "info.serving.sold.unit.value",
      type: "Radio",
      data: ["Grams", "mLs"],
      rules: ["required"],
    },
    "info.serving.prepared.unit.label": {
      section: "Nutrients",
      field: "Serving Size Unit - As Prepared",
      key: "info.serving.prepared.unit.label",
      type: "Dropdown",
      data: ["Gallon", "Grams", "mLs", "Quart", "Print", "Pound", "Fluid ounces", "Liter", "Ounces (oz)"],
      rules: ["required"],
    },
    "info.multipackValue.value": {
      section: "Product",
      field: "Multipack value",
      key: "info.multipackValue.value",
      type: "Text",
      rules: ["required"],
    },
    "info.additionalMultipackValue.value": {
      section: "Product",
      field: "Additional multipack value",
      key: "info.additionalMultipackValue.value",
      type: "Text",
      rules: ["required"],
    },
    "info.package.packageSize2.size": {
      section: "Product",
      field: "Package Size 2",
      key: "info.package.packageSize2.size",
      type: "Text",
      rules: ["required"],
    },
    "info.package.packageSize2.unit.label": {
      section: "Product",
      field: "Package size unit 2",
      key: "info.package.packageSize2.unit.label",
      type: "Dropdown",
      data: ["Gallon", "Grams", "mLs", "Quart", "Print", "Pound", "Fluid ounces", "Liter", "Ounces (oz)"],
      rules: ["required"],
    },
    "info.lowGi.presenceLogo": {
      section: "Product",
      field: "Presence Low Gi Logo",
      key: "info.lowGi.presenceLogo",
      type: "Text",
      rules: ["required"],
    },
    "info.lowGi.GlycemicIndex": {
      section: "Product",
      field: "Low GI Glycemic Index",
      key: "info.lowGi.GlycemicIndex",
      type: "Text",
      rules: ["required"],
    },
    "info.presence.di": {
      section: "Product",
      field: "Percent Di",
      key: "info.presence.di",
      type: "Text",
      rules: ["required"],
    },
    "info.presence.vegetarian": {
      section: "Product",
      field: "Presence Vegetarian",
      key: "info.presence.vegetarian",
      type: "Text",
      rules: ["required"],
    },
    "info.countryOfOriginLabelling.presence": {
      section: "Product",
      field: "Presence of Country of Origin Labelling",
      key: "info.countryOfOriginLabelling.presence",
      type: "Text",
      rules: ["required"],
    },
    "info.countryOfOriginLabelling.type.label": {
      section: "Product",
      field: "Type of Country of Origin Labelling",
      key: "info.countryOfOriginLabelling.type.label",
      type: "Dropdown",
      data: [],
      rules: ["required"],
    },
    "info.countryOfOriginLabelling.percentageStated": {
      section: "Product",
      field: "Percentage Stated On Country Of Origin Label",
      key: "info.countryOfOriginLabelling.percentageStated",
      type: "Dropdown",
      data: [],
      rules: ["required"],
    },
    "info.fssai.fsslLicNo": {
      section: "Product",
      field: "Fssai Fssl Lic No",
      key: "info.fssai.fsslLicNo",
      type: "Text",
      rules: ["required"],
    },
    "info.fssai.value": {
      section: "Product",
      field: "Presence Fssai",
      key: "info.fssai.value",
      type: "Text",
      rules: ["required"],
    },
    "info.dateLastCollected": {
      section: "Product",
      field: "Date Last Collected",
      key: "info.dateLastCollected",
      type: "Text",
      rules: ["required"],
    },
    "info.madeProducedImportedInCountry": {
      section: "Product",
      field: "Made produced imported in country",
      key: "info.madeProducedImportedInCountry",
      type: "Text",
      rules: ["required"],
    },
    "info.manufacturerDataUpdateDate": {
      section: "Product",
      field: "Manufacturer data update date",
      key: "info.manufacturerDataUpdateDate",
      type: "Text",
      rules: ["required"],
    },
    "info.EnergyOnlyReportedOnPack": {
      section: "Product",
      field: "HSR energy only reported on pack",
      key: "info.EnergyOnlyReportedOnPack",
      type: "Text",
      rules: ["required"],
    },
    "info.multipleHsrsReportedOnPack": {
      section: "Product",
      field: "Multiple HSRs reported on pack",
      key: "info.multipleHsrsReportedOnPack",
      type: "Text",
      rules: ["required"],
    },
    "info.reportedHsrOnPack": {
      section: "Product",
      field: "Reported HSR on pack",
      key: "info.reportedHsrOnPack",
      type: "Dropdown",
      data: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"],
      rules: ["required"],
    },
    "info.presenceHsr": {
      section: "Product",
      field: "Presence HSR",
      key: "info.presenceHsr",
      type: "Text",
      rules: ["required"],
    },
    "retailer.productCode": {
      section: "Product",
      field: "Retailer Product code",
      key: "retailer.productCode",
      type: "Dropdown",
      isApiCall: "retailer",
      rules: ["required"],
    },
    "info.currency": {
      section: "Product",
      field: "Currency",
      key: "info.currency",
      type: "Text",
      rules: ["required"],
    },
    "info.groups.name": {
      section: "Product",
      field: "Group Name",
      key: "info.groups.name",
      type: "Text",
      rules: ["required"],
    },
    "info.state.0": {
      section: "Product",
      field: "State Label",
      key: "info.state.0",
      type: "Text",
      data: [
        "Unreadable photos",
        "Incomplete photos",
        "Photos of multiple products",
        "Non-food item",
        "Deleted by Manufacturer",
        "Archive",
        "Recent photos (less than 2yrs old)",
        "Barcode mismatch",
        "Product labelling not in English",
        "Correct as per labelling",
      ],
      rules: ["required"],
    },
    "info.claims.otherClaimsOnPack": {
      section: "Claim",
      field: "Other Claims on Pack",
      key: "info.claims.otherClaimsOnPack",
      type: "Text",
      rules: ["required"],
    },
    "info.claimsOnPackWithValues": {
      section: "Claim",
      field: "Claims on Pack with values",
      key: "info.claimsOnPackWithValues",
      type: "DropdownInput",
      isApiCall: "claims",
      data: ["% Fat Free", "% Sugar Free", "Whole Grain"],
      rules: ["required"],
    },
    "claimProduct.0.claimClassification.0.name": {
      section: "Claim",
      field: "Claims on Pack",
      key: "claimProduct.0.claimClassification.0.name",
      type: "MultiSelect",
      isApiCall: "claims",
      data: [],
      rules: ["required"],
    },
    "info.claims.caimsOnPackAlcohol": {
      section: "Claim",
      field: "Claims on Pack - Alcohol",
      key: "info.claims.caimsOnPackAlcohol",
      type: "DoubleDropdown",
      isApiCall: "claims",
      data: ["Front", "Back", "Side", "bottom", "N/A"],
      rules: ["required"],
    },
    "info.alcohol.location.label": {
      section: "Claim",
      field: "Alcohol location",
      key: "info.alcohol.location.label",
      type: "Dropdown",
      data: ["Front", "Back", "Side", "bottom", "N/A"],
      rules: ["required"],
    },
    "info.preparedWithWaterOnly": {
      section: "Nutrients",
      field: "Prepared with water only",
      key: "info.preparedWithWaterOnly",
      type: "Checkbox",
      rules: ["required"],
    },
    "info.serving.perPack": {
      section: "Nutrients",
      field: "Servings Per Pack",
      key: "info.serving.perPack",
      type: "Text",
      rules: ["required"],
    },
    "info.serving.sold.size": {
      section: "Nutrients",
      field: "Serving Size - As Sold",
      key: "info.serving.sold.size",
      type: "Text",
      rules: ["required"],
    },
    "info.serving.prepared.size": {
      section: "Nutrients",
      field: "Serving Size - As Prepared",
      key: "info.serving.prepared.size",
      type: "Text",
      rules: ["required"],
    },
    "info.totalCarbsDisplay": {
      section: "Nutrients",
      field: "Total carbs display",
      key: "info.totalCarbsDisplay",
      type: "Checkbox",
      rules: ["required"],
    },
    "info.alcohol.percentage": {
      section: "Ingredients",
      field: "Alcohol %",
      key: "info.alcohol.percentage",
      type: "Numeric",
      rules: ["required"],
    },
    "info.standardDrinks.location.label": {
      section: "Ingredients",
      field: "Standard drinks - location",
      key: "info.standardDrinks.location.label",
      type: "Dropdown",
      data: ["Front", "Back", "Side", "bottom", "N/A"],
      rules: ["required"],
    },
    "info.lotNumberAlcoholOnly": {
      section: "Ingredients",
      field: "Lot number (alcohol only)",
      key: "info.lotNumberAlcoholOnly",
      type: "Text",
      rules: ["required"],
    },
    "info.standardDrinks.value": {
      section: "Ingredients",
      field: "Standard Drinks",
      key: "info.standardDrinks.value",
      type: "Numeric",
      rules: ["required"],
    },
    "info.gluten.label": {
      section: "Ingredients",
      field: "Gluten Status",
      key: "info.gluten.label",
      type: "Radio",
      data: ["Declared gluten free", "Gluten free by ingredients", "Contains gluten", " Naturally free", "Unknown"],
      rules: ["required"],
    },
    "info.Ingredients": {
      section: "Ingredients",
      field: "Ingredients",
      key: "info.Ingredients",
      type: "Text",
      rules: ["required"],
    },
    "info.allergens.contains": {
      section: "Ingredients",
      field: "Product Contains allergens",
      key: "info.allergens.contains",
      type: "MultiSelect",
      data: [],
      isApiCall: "allergen",
      rules: ["required"],
    },
    // "info.allergens.contains.other": {
    //   section: "Ingredients",
    //   field: "Product Contains allergens - Other",
    //   key: "info.allergens.contains.other",
    //   type: "Text",
    //   rules: ["required"],
    // },
    "info.allergens.myContains": {
      section: "Ingredients",
      field: "Product May contain allergens",
      key: "info.allergens.myContains",
      type: "MultiSelect",
      data: [],
      isApiCall: "allergen",
      rules: ["required"],
    },
    "info.allergens.mayContains.other": {
      section: "Ingredients",
      field: "Product May contain allergens - Other",
      key: "info.allergens.mayContains.other",
      type: "Text",
      rules: ["required"],
    },
    "info.notes": {
      section: "Ingredients",
      field: "User Notes",
      key: "info.notes",
      type: "Text",
      rules: ["required"],
    },
    "info.preparationInstructions.other": {
      section: "Ingredients",
      field: "Preparation Instructions Other",
      key: "info.preparationInstructions.other",
      type: "Text",
      rules: ["required"],
    },
    "info.storageTypes": {
      section: "Ingredients",
      field: "Storage type",
      key: "info.storageTypes",
      type: "MultiSelect",
      data: ["Ambient", "Chilled", "Frozen", "Other"],
      rules: ["required"],
    },
    "info.storageType.other": {
      section: "Ingredients",
      field: "Storage type other",
      key: "info.storageType.other",
      type: "Text",
      rules: ["required"],
    },
    "info.addedSugar": {
      section: "Backend",
      field: "Added Sugar",
      key: "info.addedSugar",
      type: "Numeric",
      rules: ["required"],
    },
    "info.fvnlC1": {
      section: "Backend",
      field: "FVNL - C1 %",
      key: "info.fvnlC1",
      type: "Numeric",
      rules: ["required"],
    },
    "info.addedSugarValue.estimated": {
      section: "Backend",
      field: "Added Sugar - Estimate",
      key: "info.addedSugarValue.estimated",
      type: "Numeric",
      rules: ["required"],
    },
    "info.addedSugarValue.Manufacturer": {
      section: "Backend",
      field: "Added Sugar - Manufacturer",
      key: "info.addedSugarValue.Manufacturer",
      type: "Numeric",
      rules: ["required"],
    },
    "info.addedSugarValue.Step": {
      section: "Backend",
      field: "Added Sugar - Step",
      key: "info.addedSugarValue.Step",
      type: "Dropdown",
      data: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"],
      rules: ["required"],
    },
    dataSource: {
      section: "Backend",
      field: "Data Sources",
      key: "dataSource",
      type: "Dropdown",
      data: ["Front", "Back", "Side", "bottom", "N/A"],
      rules: ["required"],
    },
    // retailer: {
    //   section: "Backend",
    //   field: "Id Retailer",
    //   key: "retailer",
    //   type: "Dropdown",
    //   isApiCall: "retailer",
    //   rules: ["required"],
    // },
    "info.vPointsC1": {
      section: "Backend",
      field: "V Points C1",
      key: "info.vPointsC1",
      type: "Numeric",
      rules: ["required"],
    },
    "info.categoryLabels": {
      section: "Backend",
      field: "Category Labels",
      key: "info.categoryLabels",
      type: "MultiSelect",
      data: ["Core", "Nova Group 4"],
      rules: ["required"],
    },
    "info.fvnl": {
      section: "Backend",
      field: "FVNL %",
      key: "info.fvnl",
      type: "Numeric",
      rules: ["required"],
    },
    "info.concentratedFvnl": {
      section: "Backend",
      field: "Concentrated FVNL %",
      key: "info.concentratedFvnl",
      type: "Numeric",
      rules: ["required"],
    },
    "info.showInHc": {
      section: "Backend",
      field: "Show in hc",
      key: "info.showInHc",
      type: "Checkbox",
      rules: ["required"],
    },
    "info.vPoints": {
      section: "Backend",
      field: "V Points",
      key: "info.vPoints",
      type: "Numeric",
      rules: ["required"],
    },
    "info.dateLastModified": {
      section: "Backend",
      field: "Date Last Modified",
      key: "info.dateLastModified",
      type: "Date",
      rules: ["required"],
    },
    "info.dateLastStatusChange": {
      section: "Backend",
      field: "Date Last Status Change",
      key: "info.dateLastStatusChange",
      type: "Date",
      rules: ["required"],
    },
    "info.infusionDate": {
      section: "Backend",
      field: "Infusion Date",
      key: "info.infusionDate",
      type: "Date",
      rules: ["required"],
    },
    "info.infusionDataSource": {
      section: "Backend",
      field: "Infusion data source",
      key: "info.infusionDataSource",
      type: "Text",
      rules: ["required"],
    },
    "info.thumbRating": {
      section: "NutrientProfiling",
      field: "Health Star Rating",
      key: "info.thumbRating",
      type: "Text",
      rules: ["required"],
    },
    "info.HSR.review": {
      section: "NutrientProfiling",
      field: "Health Star Rating Review",
      key: "info.HSR.review",
      type: "Table",
      dataHeading: ["HSR Score", "HSR TGI Score", "HSR Points", "HSR FS Points"],
      rules: ["required"],
    },
    "info.NPV.proxy.used": {
      section: "NutrientProfiling",
      field: "NPV Proxy Used",
      key: "info.NPV.proxy.used",
      type: "Table",
      dataHeading: ["HSR NPV Proxy", "TLL NPV Proxy"],
      rules: ["required"],
    },
    "info.tll.label": {
      section: "NutrientProfiling",
      field: "Traffic Lights Label",
      key: "info.tll.label",
      type: "TLTable",
      dataHeading: ["Energy", "Fat", "Saturated Fat", "Sugar", "Salt"],
      dataheadingColor: ["#ee9611", "#00c853", "#d84315", "#ee9611", "#00c853"],
      dataheadingBgColor: ["#fff8e1", "#e8ffee", "#fbe9e7", "#e8ffee", "#fff8e1"],
      legend: "Each serve (130g) contains",
      rules: ["required"],
    },
    "info.planetary.health.rating": {
      section: "NutrientProfiling",
      field: "Planetary Health Rating",
      key: "info.planetary.health.rating",
      type: "Table",
      dataHeading: ["PHR", "PHR Proxy"],
      rules: ["required"],
    },
    "info.netCarbs": {
      section: "NutrientProfiling",
      field: "Net Carbs",
      key: "info.netCarbs",
      type: "Text",
      rules: ["required"],
    },
    "info.energyFromNetCarbs": {
      section: "NutrientProfiling",
      field: "Energy from Net Carbs",
      key: "info.energyFromNetCarbs",
      type: "Text",
      rules: ["required"],
    },
    "info.diabetes.display.label": {
      section: "NutrientProfiling",
      field: "Diabetes Display Label",
      key: "info.diabetes.display.label",
      type: "TLTable",
      dataHeading: ["Energy", "Protein", "Saturated Fat", "NetCarbs", "Fibre", "Sodium", "Salt"],
      dataheadingColor: ["#ee9611", "#00c853", "#d84315", "#ee9611", "#00c853", "#d84315", "#ee9611"],
      dataheadingBgColor: ["#fff8e1", "#e8ffee", "#fbe9e7", "#e8ffee", "#fff8e1", "#fbe9e7", "#e8ffee"],
      legend: "Each per 100g contains",
      rules: ["required"],
    },
  },
};
