export const structureData = {
  Product: {
    "info.brand.name": {
      section: "Product",
      field: "Brand Name",
      key: "info.brand.name",
      type: "Text",
      filterData: ["equal to", "not equal to", "in", "not in", "is not assigned", "is assigned"],
      rules: ["required"],
      isParent: true,
    },
    "info.brand.manufacturer.name": {
      section: "Product",
      field: "Manufacturer Name",
      key: "info.brand.manufacturer.name",
      type: "Text",
      filterData: ["equal to", "not equal to", "in", "not in", "is not assigned", "is assigned"],
      rules: ["required"],
      isParent: true,
    },
    "info.importerDistributor": {
      section: "Product",
      field: "Importer/Distributor",
      key: "info.importerDistributor",
      type: "Text",
      filterData: ["equal to", "not equal to", "in", "not in", "is not assigned", "is assigned"],
      rules: ["required"],
      isParent: true,
    },
    "info.brand.brandOther": {
      section: "Product",
      field: "Brand Other",
      key: "info.brand.brandOther",
      type: "Text",
      rules: ["required"],
      isParent: true,
    },
    "name.default": {
      section: "Product",
      field: "Product Name",
      key: "name.default",
      type: "Text",
      rules: ["required"],
      isParent: true,
    },
    "info.package.packageSize1.size": {
      section: "Product",
      field: "Package Size",
      key: "info.package.packageSize1.size",
      type: "Text",
      rules: ["required"],
      isParent: true,
    },
    "info.package.packageSize1.unit.label": {
      section: "Product",
      field: "Package Unit",
      key: "info.package.packageSize1.unit.label",
      type: "Radio",
      data: ["Grams", "mLs"],
      rules: ["required"],
      isParent: true,
    },
    "info.multipackValue.value": {
      section: "Product",
      field: "Multipack value",
      key: "info.multipackValue.value",
      type: "Text",
      rules: ["required"],
      isParent: true,
    },
    "info.additionalMultipackValue.value": {
      section: "Product",
      field: "Additional multipack value",
      key: "info.additionalMultipackValue.value",
      type: "Text",
      rules: ["required"],
      isParent: true,
    },
    "info.package.packageSize2.size": {
      section: "Product",
      field: "Package Size 2",
      key: "info.package.packageSize2.size",
      type: "Text",
      rules: ["required"],
      isParent: true,
    },
    "info.package.packageSize2.unit.label": {
      section: "Product",
      field: "Package size unit 2",
      key: "info.package.packageSize2.unit.label",
      type: "Dropdown",
      data: ["Gallon", "Grams", "mLs", "Quart", "Print", "Pound", "Fluid ounces", "Liter", "Ounces (oz)"],
      rules: ["required"],
      isParent: true,
    },
    "info.lowGi.presenceLogo": {
      section: "Product",
      field: "Presence Low Gi Logo",
      key: "info.lowGi.presenceLogo",
      type: "Checkbox",
      rules: ["required"],
      isParent: true,
    },
    "info.lowGi.GlycemicIndex": {
      section: "Product",
      field: "Low GI Glycemic Index",
      key: "info.lowGi.GlycemicIndex",
      type: "Text",
      rules: ["required"],
      isParent: true,
    },
    "info.presence.di": {
      section: "Product",
      field: "Percent Di",
      key: "info.presence.di",
      type: "Checkbox",
      rules: ["required"],
      isParent: true,
    },
    "info.presence.vegetarian": {
      section: "Product",
      field: "Vegetarian",
      key: "info.presence.vegetarian",
      type: "Checkbox",
      rules: ["required"],
      isParent: true,
    },
    "info.countryOfOriginLabelling.presence": {
      section: "Product",
      field: "Presence of Country of Origin Labelling",
      key: "info.countryOfOriginLabelling.presence",
      type: "Checkbox",
      rules: ["required"],
      isParent: true,
    },
    "info.countryOfOriginLabelling.type.label": {
      section: "Product",
      field: "Type of Country of Origin Labelling",
      key: "info.countryOfOriginLabelling.type.label",
      type: "Dropdown",
      data: [],
      rules: ["required"],
      isParent: true,
    },
    "info.countryOfOriginLabelling.percentageStated": {
      section: "Product",
      field: "Percentage Stated On Country Of Origin Label",
      key: "info.countryOfOriginLabelling.percentageStated",
      type: "Dropdown",
      data: [],
      rules: ["required"],
      isParent: true,
    },
    "info.fssai.fsslLicNo": {
      section: "Product",
      field: "Fssai Fssl Lic No",
      key: "info.fssai.fsslLicNo",
      type: "Text",
      rules: ["required"],
      isParent: true,
    },
    "info.fssai.value": {
      section: "Product",
      field: "Presence Fssai",
      key: "info.fssai.value",
      type: "Checkbox",
      rules: ["required"],
      isParent: true,
    },
    "info.dateLastCollected": {
      section: "Product",
      field: "Date Last Collected",
      key: "info.dateLastCollected",
      type: "Date",
      rules: ["required"],
      isParent: true,
    },
    "info.madeProducedImportedInCountry": {
      section: "Product",
      field: "Made produced imported in country",
      key: "info.madeProducedImportedInCountry",
      type: "Text",
      rules: ["required"],
      isParent: true,
    },
    "info.manufacturerDataUpdateDate": {
      section: "Product",
      field: "Manufacturer data update date",
      key: "info.manufacturerDataUpdateDate",
      type: "Date",
      rules: ["required"],
      isParent: true,
    },
    "info.EnergyOnlyReportedOnPack": {
      section: "Product",
      field: "HSR energy only reported on pack",
      key: "info.EnergyOnlyReportedOnPack",
      type: "Checkbox",
      rules: ["required"],
      isParent: true,
    },
    "info.multipleHsrsReportedOnPack": {
      section: "Product",
      field: "Multiple HSRs reported on pack",
      key: "info.multipleHsrsReportedOnPack",
      type: "Checkbox",
      rules: ["required"],
      isParent: true,
    },
    "info.reportedHsrOnPack": {
      section: "Product",
      field: "Reported HSR on pack",
      key: "info.reportedHsrOnPack",
      type: "Dropdown",
      data: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"],
      rules: ["required"],
      isParent: true,
    },
    "info.presenceHsr": {
      section: "Product",
      field: "Presence HSR",
      key: "info.presenceHsr",
      type: "Checkbox",
      rules: ["required"],
      isParent: true,
    },
    retailerProductCode: {
      section: "Product",
      field: "Retailer Product code",
      key: "retailerProductCode",
      type: "GenericChildFields",
      isApiCall: "retailer",
      rules: ["required"],
      children: [
        "retailerProductCode.$.name",
        "retailerProductCode.$.retailerProductCode",
        "retailerProductCode.$.date",
      ],
      isParent: true,
    },
    "retailerProductCode.$.name": {
      section: "Product",
      isApiCall: "retailer",
      field: "Choose retailer",
      key: "retailerProductCode.$.name",
      type: "Dropdown",
      data: [],
      isParent: false,
    },
    "retailerProductCode.$.retailerProductCode": {
      section: "Product",
      field: "Enter code",
      key: "retailerProductCode.$.retailerProductCode",
      type: "Numeric",
      isParent: false,
    },
    "retailerProductCode.$.date": {
      section: "Product",
      field: "Choose date",
      key: "retailerProductCode.$.date",
      type: "Date",
      isParent: false,
    },
    "info.currency": {
      section: "Product",
      field: "Currency",
      key: "info.currency",
      type: "Text",
      rules: ["required"],
      isParent: true,
    },
    "info.groups.name": {
      section: "Product",
      field: "Group Name",
      key: "info.groups.name",
      type: "Text",
      rules: {
        isReadonly: true,
      },
    },
    "info.state.0": {
      section: "Product",
      field: "State Label",
      key: "info.state.0",
      type: "MultiSelect",
      data: [
        "Unreadable photos",
        "Incomplete photos",
        "Photos of multiple products",
        "Non-food item",
        "Deleted by Manufacturer",
        "Archive",
        "Recent photos (less than 2yrs old)",
        "Barcode mismatch",
        "Product labelling not in English",
        "Correct as per labelling",
      ],
      rules: ["required"],
      isParent: true,
    },
  },
  Claim: {
    "info.claims.otherClaimsOnPack": {
      section: "Claim",
      field: "Other Claims on Pack",
      key: "info.claims.otherClaimsOnPack",
      type: "Text",
      rules: ["required"],
      isParent: true,
    },
    claimsOnPackWithValues: {
      section: "Claim",
      field: "Claims on Pack with values",
      key: "claimsOnPackWithValues",
      type: "GenericChildFields",
      isApiCall: "claims",
      data: ["% Fat Free", "% Sugar Free", "Whole Grain"],
      rules: ["required"],
      children: ["claimsOnPackWithValues.$.name", "claimsOnPackWithValues.$.value"],
      isParent: true,
    },
    "claimsOnPackWithValues.$.name": {
      section: "Claim",
      field: "Choose Claim",
      key: "claimsOnPackWithValues.$.name",
      isApiCall: "claims",
      type: "Dropdown",
      isParent: false,
    },
    "claimsOnPackWithValues.$.value": {
      section: "Claim",
      field: "Enter value",
      key: "claimsOnPackWithValues.$.value",
      type: "Numeric",
      isParent: false,
    },
    "claimProduct.0.claimClassification.0.name": {
      section: "Claim",
      field: "Claims on Pack",
      key: "claimProduct.0.claimClassification.0.name",
      type: "MultiSelect",
      isApiCall: "claims",
      data: [],
      rules: ["required"],
      isParent: true,
    },
    claimProduct: {
      section: "Claim",
      field: "Claims on Pack - Alcohol",
      key: "claimProduct",
      type: "GenericChildFields",
      isApiCall: "claims",
      data: ["Front", "Back", "Side", "bottom", "N/A"],
      rules: ["required"],
      children: ["claimProduct.$.name", "claimProduct.$.location"],
      isParent: true,
    },
    "claimProduct.$.name": {
      section: "Claim",
      field: "Choose Claim",
      key: "claimProduct.$.name",
      isApiCall: "claims",
      type: "Dropdown",
      isParent: false,
    },
    "claimProduct.$.location": {
      section: "Claim",
      field: "Choose Location",
      key: "claimProduct.$.location",
      type: "Dropdown",
      data: ["Front", "Back", "Side", "bottom", "N/A"],
      isParent: false,
    },
    "info.alcohol.location.label": {
      section: "Claim",
      field: "Alcohol location",
      key: "info.alcohol.location.label",
      type: "Dropdown",
      data: ["Front", "Back", "Side", "bottom", "N/A"],
      rules: ["required"],
      isParent: true,
    },
  },
  Nutrients: {
    "info.nipType.label": {
      section: "Nutrients",
      field: "Nip Type",
      key: "info.nipType.label",
      type: "Dropdown",
      data: ["Standard", "No Nip", "Multiple Nip", "USA Nip", "Standard Plus", "EU Standard", "EU Standard Plus"],
      rules: ["required"],
      isParent: true,
    },
    "info.preparedWithWaterOnly": {
      section: "Nutrients",
      field: "Prepared with water only",
      key: "info.preparedWithWaterOnly",
      type: "Checkbox",
      rules: ["required"],
      isParent: true,
    },
    "info.serving.perPack": {
      section: "Nutrients",
      field: "Servings Per Pack",
      key: "info.serving.perPack",
      type: "Text",
      rules: ["required"],
      isParent: true,
    },
    "info.serving.sold.size": {
      section: "Nutrients",
      field: "Serving Size - As Sold",
      key: "info.serving.sold.size",
      type: "Text",
      rules: ["required"],
      isParent: true,
    },
    "info.serving.sold.unit.value": {
      section: "Nutrients",
      field: "Serving Size Unit - As Sold",
      key: "info.serving.sold.unit.value",
      type: "Radio",
      data: ["Grams", "mLs"],
      rules: ["required"],
      isParent: true,
    },
    "info.serving.prepared.size": {
      section: "Nutrients",
      field: "Serving Size - As Prepared",
      key: "info.serving.prepared.size",
      type: "Text",
      rules: ["required"],
      isParent: true,
    },
    "info.serving.prepared.unit.label": {
      section: "Nutrients",
      field: "Serving Size Unit - As Prepared",
      key: "info.serving.prepared.unit.label",
      type: "Dropdown",
      data: ["Gallon", "Grams", "mLs", "Quart", "Print", "Pound", "Fluid ounces", "Liter", "Ounces (oz)"],
      rules: ["required"],
      isParent: true,
    },
    "info.totalCarbsDisplay": {
      section: "Nutrients",
      field: "Total carbs display",
      key: "info.totalCarbsDisplay",
      type: "Checkbox",
      rules: ["required"],
      isParent: true,
    },
  },
  Ingredients: {
    "info.alcohol.percentage": {
      section: "Ingredients",
      field: "Alcohol %",
      key: "info.alcohol.percentage",
      type: "Numeric",
      rules: ["required"],
      isParent: true,
    },
    "info.standardDrinks.location.label": {
      section: "Ingredients",
      field: "Standard drinks - location",
      key: "info.standardDrinks.location.label",
      type: "Dropdown",
      data: ["Front", "Back", "Side", "bottom", "N/A"],
      rules: ["required"],
      isParent: true,
    },
    "info.lotNumberAlcoholOnly": {
      section: "Ingredients",
      field: "Lot number (alcohol only)",
      key: "info.lotNumberAlcoholOnly",
      type: "Text",
      rules: ["required"],
      isParent: true,
    },
    "info.standardDrinks.value": {
      section: "Ingredients",
      field: "Standard Drinks",
      key: "info.standardDrinks.value",
      type: "Numeric",
      rules: ["required"],
      isParent: true,
    },
    "info.gluten.label": {
      section: "Ingredients",
      field: "Gluten Status",
      key: "info.gluten.label",
      type: "Radio",
      data: ["Declared gluten free", "Gluten free by ingredients", "Contains gluten", " Naturally free", "Unknown"],
      rules: ["required"],
      isParent: true,
    },
    "info.Ingredients": {
      section: "Ingredients",
      field: "Ingredients",
      key: "info.Ingredients",
      type: "Text",
      rules: ["required"],
      isParent: true,
    },
    "info.allergens.contains": {
      section: "Ingredients",
      field: "Product Contains allergens",
      key: "info.allergens.contains",
      type: "MultiSelect",
      data: [],
      isApiCall: "allergen",
      rules: ["required"],
      isParent: true,
    },
    "info.allergens.contains.other": {
      section: "Ingredients",
      field: "Product Contains allergens - Other",
      key: "info.allergens.contains.other",
      type: "Text",
      rules: ["required"],
      isParent: true,
    },
    "info.allergens.myContains": {
      section: "Ingredients",
      field: "Product May contain allergens",
      key: "info.allergens.myContains",
      type: "MultiSelect",
      data: [],
      isApiCall: "allergen",
      rules: ["required"],
      isParent: true,
    },
    "info.allergens.mayContains.other": {
      section: "Ingredients",
      field: "Product May contain allergens - Other",
      key: "info.allergens.mayContains.other",
      type: "Text",
      rules: ["required"],
      isParent: true,
    },
    "info.notes": {
      section: "Ingredients",
      field: "User Notes",
      key: "info.notes",
      type: "Text",
      rules: ["required"],
      isParent: true,
    },
    preparationInstructions: {
      section: "Ingredients",
      field: "Preparation Instructions ",
      key: "preparationInstructions",
      type: "GenericChildFields",
      rules: ["required"],
      children: [
        "preparationInstructions.$.type",
        "preparationInstructions.$.temprature",
        "preparationInstructions.$.level",
        "preparationInstructions.$.time",
        "preparationInstructions.$.Weight",
      ],
      isParent: true,
    },
    "preparationInstructions.$.type": {
      section: "Ingredients",
      field: "Choose Preparation Type",
      key: "preparationInstructions.$.type",
      type: "Dropdown",
      data: [
        "No prep required",
        "Microwave",
        "Oven",
        "Sandwitch press/toaster",
        "BBQ",
        "Stove top",
        "Grill",
        "Add boiling water",
        "Add cold liquid",
        "other",
      ],
      isParent: false,
    },
    "preparationInstructions.$.temprature": {
      section: "Ingredients",
      field: "Temp",
      key: "preparationInstructions.$.temprature",
      type: "Dropdown",
      data: ["Low", "Medium", "High"],
      isParent: false,
    },
    "preparationInstructions.$.level": {
      section: "Ingredients",
      field: "Temp Up",
      key: "preparationInstructions.$.level",
      type: "Dropdown",
      data: ["true", "false"],
      isParent: false,
    },
    "preparationInstructions.$.time": {
      section: "Ingredients",
      field: "Time (mins)",
      key: "preparationInstructions.$.time",
      type: "Text",
      isParent: false,
    },
    "preparationInstructions.$.Weight": {
      section: "Ingredients",
      field: "Time Per",
      key: "preparationInstructions.$.Weight",
      type: "Dropdown",
      data: ["Per Kg", "Per serve/pack"],
      isParent: false,
    },
    "info.preparationInstructions.other": {
      section: "Ingredients",
      field: "Preparation Instructions Other",
      key: "info.preparationInstructions.other",
      type: "Text",
      rules: ["required"],
      isParent: true,
    },
    "info.storageTypes": {
      section: "Ingredients",
      field: "Storage type",
      key: "info.storageTypes",
      type: "MultiSelect",
      data: ["Ambient", "Chilled", "Frozen", "Other"],
      rules: ["required"],
      isParent: true,
    },
    "info.storageType.other": {
      section: "Ingredients",
      field: "Storage type other",
      key: "info.storageType.other",
      type: "Text",
      rules: ["required"],
      isParent: true,
    },
  },
  Backend: {
    "info.addedSugar": {
      section: "Backend",
      field: "Added Sugar",
      key: "info.addedSugar",
      type: "Numeric",
      rules: ["required"],
      isParent: true,
    },
    "info.fvnlC1": {
      section: "Backend",
      field: "FVNL - C1 %",
      key: "info.fvnlC1",
      type: "Numeric",
      rules: ["required"],
      isParent: true,
    },
    "info.addedSugarValue.estimated": {
      section: "Backend",
      field: "Added Sugar - Estimate",
      key: "info.addedSugarValue.estimated",
      type: "Numeric",
      rules: ["required"],
      isParent: true,
    },
    "info.addedSugarValue.Manufacturer": {
      section: "Backend",
      field: "Added Sugar - Manufacturer",
      key: "info.addedSugarValue.Manufacturer",
      type: "Numeric",
      rules: ["required"],
      isParent: true,
    },
    "info.addedSugarValue.Step": {
      section: "Backend",
      field: "Added Sugar - Step",
      key: "info.addedSugarValue.Step",
      type: "Dropdown",
      data: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"],
      rules: ["required"],
      isParent: true,
    },
    dataSource: {
      section: "Backend",
      field: "Data Sources",
      key: "dataSource",
      type: "GenericChildFields",
      data: ["Front", "Back", "Side", "bottom", "N/A"],
      rules: ["required"],
      children: ["dataSource.$.name", "dataSource.$.date"],
      isParent: true,
    },
    "dataSource.$.name": {
      section: "Backend",
      field: "Choose Data Source",
      key: "dataSource.$.name",
      type: "Dropdown",
      data: ["Front", "Back", "Side", "bottom", "N/A"],
      isParent: false,
    },
    "dataSource.$.date": {
      section: "Backend",
      field: "Choose Date",
      key: "dataSource.$.date",
      type: "Date",
      isParent: false,
    },
    retailer: {
      section: "Backend",
      field: "Id Retailer",
      key: "retailer",
      type: "GenericChildFields",
      isApiCall: "retailer",
      rules: ["required"],
      children: ["retailers.$.name", "retailers.$.storename", "retailers.$.date"],
      isParent: true,
    },
    "retailers.$.name": {
      section: "Backend",
      isApiCall: "retailer",
      field: "Choose Retailer",
      key: "retailers.$.name",
      type: "Dropdown",
      // data: ["Core", "Nova Group 1"],
      isParent: false,
    },
    "retailers.$.storename": {
      section: "Backend",
      field: "Enter store name",
      key: "retailers.$.storename",
      type: "Text",
      isParent: false,
    },
    "retailers.$.date": {
      section: "Backend",
      field: "Choose date",
      key: "retailers.$.date",
      type: "Date",
      isParent: false,
    },

    "info.vPointsC1": {
      section: "Backend",
      field: "V Points C1",
      key: "info.vPointsC1",
      type: "Numeric",
      rules: ["required"],
      isParent: true,
    },
    "info.categoryLabels": {
      section: "Backend",
      field: "Category Labels",
      key: "info.categoryLabels",
      type: "MultiSelect",
      // data: ["Core", "Nova Group 1"],
      rules: ["required"],
      isParent: true,
    },
    productLabelsAllocated: {
      section: "Backend",
      field: "Category Label Groups",
      key: "productLabelsAllocated",
      type: "MultiSelect",
      // data: [],
      rules: ["required"],
      isParent: true,
    },
    "info.fvnl": {
      section: "Backend",
      field: "FVNL %",
      key: "info.fvnl",
      type: "Numeric",
      rules: ["required"],
      isParent: true,
    },
    "info.ghge": {
      section: "Backend",
      field: "GHGe",
      key: "info.ghge",
      type: "Numeric",
      rules: ["required"],
      isParent: true,
    },
    "info.concentratedFvnl": {
      section: "Backend",
      field: "Concentrated FVNL %",
      key: "info.concentratedFvnl",
      type: "Numeric",
      rules: ["required"],
      isParent: true,
    },
    "info.isConcentrate": {
      section: "Backend",
      field: "Is Concentrate",
      key: "info.isConcentrate",
      type: "Checkbox",
      rules: ["required"],
      isParent: true,
    },
    "info.showInHc": {
      section: "Backend",
      field: "Show in hc",
      key: "info.showInHc",
      type: "Checkbox",
      rules: ["required"],
      isParent: true,
    },
    "info.vPoints": {
      section: "Backend",
      field: "V Points",
      key: "info.vPoints",
      type: "Numeric",
      rules: ["required"],
      isParent: true,
    },
    "info.dateLastModified": {
      section: "Backend",
      field: "Date Last Modified",
      key: "info.dateLastModified",
      type: "Date",
      rules: ["required"],
      isParent: true,
    },
    "info.dateLastStatusChange": {
      section: "Backend",
      field: "Date Last Status Change",
      key: "info.dateLastStatusChange",
      type: "Date",
      rules: ["required"],
      isParent: true,
    },
    "info.infusionDate": {
      section: "Backend",
      field: "Infusion Date",
      key: "info.infusionDate",
      type: "Date",
      rules: ["required"],
      isParent: true,
    },
    "info.infusionDataSource": {
      section: "Backend",
      field: "Infusion data source",
      key: "info.infusionDataSource",
      type: "Text",
      rules: ["required"],
      isParent: true,
    },
  },
  NutrientProfiling: {
    "info.thumbRating": {
      section: "NutrientProfiling",
      field: "Health Star Rating",
      key: "info.thumbRating",
      type: "Text",
      rules: ["required"],
      isParent: true,
    },
    "info.HSR.review": {
      section: "NutrientProfiling",
      field: "Health Star Rating Review",
      key: "info.HSR.review",
      type: "Table",
      dataHeading: ["HSR Score", "HSR TGI Score", "HSR Points", "HSR FS Points"],
      rules: ["required"],
      isParent: true,
    },
    "info.NPV.proxy.used": {
      section: "NutrientProfiling",
      field: "NPV Proxy Used",
      key: "info.NPV.proxy.used",
      type: "Table",
      dataHeading: ["HSR NPV Proxy", "TLL NPV Proxy"],
      rules: ["required"],
      isParent: true,
    },
    "info.tll.label": {
      section: "NutrientProfiling",
      field: "Traffic Lights Label",
      key: "info.tll.label",
      type: "TLTable",
      dataHeading: ["Energy", "Fat", "Saturated Fat", "Sugar", "Salt", "Net Carbs", "Protein", "Fibre"],
      dataheadingColor: ["#ee9611", "#00c853", "#d84315", "#ee9611", "#00c853", "#7f7f7f", "#00c853", "#d84315"],
      dataheadingBgColor: ["#fff8e1", "#e8ffee", "#fbe9e7", "#fff8e1", "#e8ffee", "#e8e6e6", "#e8ffee", "#fbe9e7"],
      legend: "Each serve (130g) contains",
      rules: ["required"],
      isParent: true,
    },
    "info.hsr.hsrNa": {
      section: "NutrientProfiling",
      field: "Hsr Na",
      key: "info.hsr.hsrNa",
      type: "Text",
      rules: ["required"],
      isParent: true,
    },
    "info.hsr.hsrNaDescr": {
      section: "NutrientProfiling",
      field: "Hsr Na Descr",
      key: "info.hsr.hsrNaDescr",
      type: "Text",
      rules: ["required"],
      isParent: true,
    },
    "info.planetary.health.rating": {
      section: "NutrientProfiling",
      field: "Planetary Health Rating",
      key: "info.planetary.health.rating",
      type: "Table",
      dataHeading: ["PHR", "PHR Proxy"],
      rules: ["required"],
      isParent: true,
    },
    "info.netCarbs": {
      section: "NutrientProfiling",
      field: "Net Carbs",
      key: "info.netCarbs",
      type: "Text",
      rules: ["required"],
      isParent: true,
    },
    "info.energyFromNetCarbs": {
      section: "NutrientProfiling",
      field: "Energy from Net Carbs",
      key: "info.energyFromNetCarbs",
      type: "Text",
      rules: ["required"],
      isParent: true,
    },
    "info.diabetes.display.label": {
      section: "NutrientProfiling",
      field: "Diabetes Display Label",
      key: "info.diabetes.display.label",
      type: "TLTable",
      dataHeading: ["Energy", "Protein", "Saturated Fat", "NetCarbs", "Fibre", "Sodium", "Salt"],
      dataheadingColor: ["#ee9611", "#00c853", "#d84315", "#ee9611", "#00c853", "#d84315", "#ee9611"],
      dataheadingBgColor: ["#fff8e1", "#e8ffee", "#fbe9e7", "#e8ffee", "#fff8e1", "#fbe9e7", "#e8ffee"],
      legend: "Each per 100g contains",
      rules: ["required"],
      isParent: true,
    },
  },
  Group: {
    "category/groupcode": {
      section: "Claim",
      field: "Category/Group Search",
      key: "category/groupcode",
      type: "DoubleInput",
      isApiCall: "claims",
      data: ["Front", "Back", "Side", "bottom", "N/A"],
      rules: ["required"],
      isParent: true,
    },
  },
};
